#!/usr/bin/env python
import yaml
import subprocess


def sh(cmd):
    return subprocess.check_output(cmd.split()).strip()


hostname = sh('relation-get hostname')
port = sh('relation-get port')

if not hostname or not port:
    sh('juju-log hostname or port not found')
    sys.exit(1)

with open('/etc/gandalf.conf') as fp:
    conf = yaml.load(fp)

conf.update({
    'database': {
        'name': 'gandalf',
        'url': '%s:%s' % (hostname, port)
    }
})

with open('/etc/gandalf.conf', 'wb') as fp:
    yaml.dump(conf, fp, default_flow_style=False)

sh('./hooks/restart')

