#!/usr/bin/env python
import yaml
import subprocess


def sh(*args):
    return subprocess.check_output(*args).strip()


bind = sh('config-get bind')

with open('/etc/gandalf.conf') as fp:
    conf = yaml.load(fp)

conf['bind'] = bind

with open('/etc/gandalf.conf', 'wb') as fp:
    yaml.dump(conf, fp)

sh('open-port %s/tcp' % bind.split(':')[1])
sh('./hooks/restart')

