#!/bin/bash
sudo apt-add-repository -y ppa:tsuru/ppa
sudo apt-get update -y
sudo apt-get install -y gandalf-server

# Create git user
useradd --create-home git
sudo -u git mkdir /home/git/.ssh
sudo chown git:git /home/git/.ssh
sudo chmod 0700 /home/git/.ssh

